name: ci-testing
on: [ push, pull_request ]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - run: go generate ./...
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: test
        run: make test

  testacc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        netbox-version:
          - "v3.1.11"
          - "v3.1.10"
          - "v3.1.9"
          - "v3.1.8"
          - "v3.1.7"
          - "v3.1.6"
          - "v3.1.5"
          - "v3.1.4"
          - "v3.1.3"
          - "v3.1.2"
          - "v3.1.1"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: testacc
        run: make -e testacc
        env:
          NETBOX_VERSION: ${{ matrix.netbox-version }}
